### ISSUE TITLE
support of import package?

### ISSUE THREAD

**Issue by paddyroddy** [sylvainhalle/textidote#129]
I was using the `import` package mainly to avoid absolute paths but I really wanted to use this tool so, for now, am using `\input` commands. Could this be done?

**Comment by sylvainhalle** [comment]
This is related to #81, where there is an ongoing discussion about supporting various "sub-file" mechanisms.

My main concern is that I now discover there is more than one way of doing so:

- use the `import` package
- use the `subfiles` package

and they seem to work in different ways. Supporting them all would more or less amount to reimplement the package's functionality within TeXtidote so that it finds the same files in the same way. In my opinion, that would be a case of #56.

**Comment by paddyroddy** [comment]
okay no worries, I'm using `\input` now to be compatible

**Comment by sylvainhalle** [comment]
Thanks for your understanding. I'm already struggling to update the software to resolve bugs!

**Comment by sylvainhalle** [comment]
May I suggest we move this discussion to #131
