### ISSUE TITLE
Other files are not included if --clean argument is provided

### ISSUE THREAD

**Issue by Jendker** [sylvainhalle/textidote#132]
Is there any way to get in the output other files included using `\input` if `--clean` argument is used?
Inclusion works fine if I don't use the `--clean` argument.

**Comment by SheldonZhong** [comment]
There is a workaround. First remove all the `\input` using a perl script then use `textidote --clean`.
See [here](https://tex.stackexchange.com/questions/21838/replace-inputfilex-by-the-content-of-filex-automatically/377404).

**Comment by sylvainhalle** [comment]
One thing to know is that TeXtidote does not "include" sub-files inside the main file in order to process them: rather, it processes the main file, and _then_ processes any sub-file separately if `\input` instructions are found. So it is normal that the `--clean` option only cleans the main file. I'll mark this as _wontfix_ and suggest you use the solution mentioned above in this thread.
