### ISSUE TITLE
--remove-macros does not remove macro before full stop

### ISSUE THREAD

**Issue by bratekarate** [sylvainhalle/textidote#144]
If the macro is at the end of the sentence, right before a full stop, it is not removed.

The following tests were run with `--remove-macros parencite,todo`

Not removed:
```latex
This is a poorly worded sentence \todo{rewrite this sentence}.
```
```latex
This sentence needs a citation \parencite{source}. However, ...
```

Removed:
```latex
 \todo{rewrite this sentence} This is a poorly worded sentence.
```
```latex
\This sentence needs a citation. \parencite{source} However, ...
```
For macros like `\todo` it does not really matter that much, they can be put at the start of the sentence. But macros like `\parencite`  must placed before the full stop, so the citation is inserted properly.

**Comment by sylvainhalle** [comment]
This line and the following:

https://github.com/sylvainhalle/textidote/blob/9cd25a648074314f9b8cef91c47972913aed0a26/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L149

Instead of using `\s` (space) at the end of the macro name, it should be `\b` (word boundary). Should fix the problem.

**Comment by bratekarate** [comment]
I would check it out myself, but right now I am loaded with work. When I have more time in the future, I would be happy to contribute to this project more often.
