### ISSUE TITLE
Support of LSP for usage with coc.nvim

### ISSUE THREAD

**Issue by arminWel** [sylvainhalle/textidote#163]
To efficiently use textidote, I'd like to use as it as a Language Server with the LSP so that I can include it into [coc.nvim](https://github.com/neoclide/coc.nvim). Is this already supported, or is this a possible enhancement?

**Comment by sylvainhalle** [comment]
I wasn't aware of LSP, so thanks for this message. However I looked at what it is, and it looks like some pretty heavy functionality that is not really the core of TeXtidote. I'd see this more as a separate project that uses TeXtidote, rather than including it directly into the tool. So for now, I'll mark this as a wontfix.
