### ISSUE TITLE
eqnarray not recognized as latex environment

### ISSUE THREAD

**Issue by frevandonanet** [sylvainhalle/textidote#167]
First of all, I would like to congratulate you for the very handy program. I just started using textidot and found it very useful. I noticed though that it seems not to be aware of eqnarrays. It smartly skips equations when surrounded by \begin{equation} ... \end{equation}, but the same does not hold with eqnarray (I think it also does not work with $$ ... $$). Is there a way to make it work for such cases?
Thanks in advance.

**Comment by sylvainhalle** [comment]
Thanks! Is it possible that you are using the starred version `eqnarray*`? If so, then the issue is this line:

https://github.com/sylvainhalle/textidote/blob/ab9de53c1fe7a04826a98850c75d3f4fb6a0811e/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L342

It recongnizes `eqnarray` as an environment to ignore, but not `eqnarray*`.

**Comment by sylvainhalle** [comment]
OK, I found the issue; it turns out that TeXtidote does not remove `eqnarray` at all. I will push a commit that fixes this issue.

In the meantime, a workaround using the current version is to use the `--remove` command line option:

    textidote --remove eqnarray myfile.tex
