### ISSUE TITLE
Running Textidote in a make file

### ISSUE THREAD

**Issue by linuxscout** [sylvainhalle/textidote#187]
Hi,
I used to make my commands on a makefile, to facilitate the reuse of command,

I have this  in my Makefile
```makefile
check: 
     cd myfolder;textidote chapters/chapitre0.tex> ../output/report-fr.html
```
The output is 
```
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain Hall? - All rights reserved

Using replacement file replacement.txt
Found 0 warning(s)
Total analysis time: 0 second(s)
```

If I try it on the command line, like this:
```sh
$cd myfolder
$ textidote chapters/chapitre0.tex> ../output/report-fr.html
```
It gives 
```shell
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain Hallé - All rights reserved

Using replacement file replacement.txt
Found 120 warning(s)
Total analysis time: 3 second(s)

```
I try to run it, as jar file, like this
```
$ java -jar /opt/textidote/textidote.jar --name textidote chapters/chapitre0.tex> ../output/report-fr.html
```
but it gives the same result (in makefile no error, in shell, more errors.

I works on Ubuntu linux.

Thanks

**Comment by sylvainhalle** [comment]
Hi,
I cannot reproduce the bug using the setup and Makefile you describe. On my side, calling `make` or calling TeXtidote directly has the same effect (and errors are found).

The fact that the analysis takes 0 second instead of 3 on your side probably indicates that TeXtidote is not processing anything. This typically occurs if the file does not contain a `\begin{document}` and the `--read-all` argument is not present (#76).

I see that a replacement file is mentioned, even though none is passed as a command line parameter. This is only possible if a `.textidote` file is present (see [Using a configuration file](https://github.com/sylvainhalle/textidote#using-a-configuration-file)). Could it be possible that this same file contain other parameters?

**Comment by linuxscout** [comment]
Thanks,
I used the following .texidote file:
```
--read-all
--output html
--check fr
--remove arab
--dict dict.txt
--remove-macros aRL
--replace replacement.txt
```

The result is the same if I put parameters in make file,

I will try other if I can find another way to do this.
Thanks
