### ISSUE TITLE
Silent output

### ISSUE THREAD

**Issue by da1ight** [sylvainhalle/textidote#211]
Hi!
Thanks for your tool it is exactly what I'am looking for)
One short question, I have been started analysis with the following command:

`find . -name "*.tex" -exec java -jar textidote.jar --output singleline {} \;`

I have seen a lot of empty lines and such messages in the output:

```
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain Hallé - All rights reserved

Found 0 warning(s)
Total analysis time: 0 second(s)
```

Is there any way to run the analysis in a less verbose mode? I need to pass it to a file eventually.

**Comment by sylvainhalle** [comment]
The last two lines are printed to the standard error, so if you only redirect the standard output to a file you won't see them.

However the same should be done with the first two lines; the culprit is here:

https://github.com/sylvainhalle/textidote/blob/4e3a589a0652329e4a630d9119c05c7a2845d8dc/Source/Core/src/ca/uqac/lif/textidote/Main.java#L226

**Comment by da1ight** [comment]
Line 226? May be that was a mistake?
https://github.com/sylvainhalle/textidote/blob/4e3a589a0652329e4a630d9119c05c7a2845d8dc/Source/Core/src/ca/uqac/lif/textidote/Main.java#L229
`find . -name "*.tex" -exec java -jar textidote.jar --check en --quiet --output singleline {} \;`
Option `--quiet` does exactly what I'm trying to achieve. Thank you.
