### ISSUE TITLE
Stack Overflow Error When Using French Check Option --check fr

### ISSUE THREAD

**Issue by Biorix** [sylvainhalle/textidote#218]
Using the `--check` with fr option yield a StackOverflow error :

English, Deutsch, Espanol works:
```
java -jar textidote.jar --check en intro.tex
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain HallΘ - All rights reserved

Found 19 warning(s)
Total analysis time: 1 second(s)
```
```
java -jar textidote.jar --check de intro.tex
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain HallΘ - All rights reserved

Found 19 warning(s)
Total analysis time: 3 second(s)
```

But when using French:
```
java -jar textidote.jar --check fr intro.tex
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain HallΘ - All rights reserved

Exception in thread "main" java.lang.StackOverflowError
        at java.util.stream.Streams$ConcatSpliterator.estimateSize(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.estimateSize(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.estimateSize(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.estimateSize(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.estimateSize(Unknown Source)
        ....
```

**Comment by Biorix** [comment]
Sorry, I didn't see the response.
I tried with different files and I have the same exception.

Here is the file 
[intro.zip](https://github.com/sylvainhalle/textidote/files/10922815/intro.zip)

**Comment by sylvainhalle** [comment]
1. With the file you provided, you must use the `--read-all` option otherwise nothing will be analyzed. I assume this is what you typed.

2. I am still unable to reproduce the bug. On my computer TeXtidote analyzes the file in 6 seconds.

I just put online a new release (https://github.com/sylvainhalle/textidote/releases/tag/v0.9). Could you please check if you still have the issue with this version?

**Comment by Biorix** [comment]
I'm not certain what you mean. I typed what I put in my previous message : 
```java -jar textidote.jar --check fr intro.tex```

I have a response with other languages, just not in French.

The result with :
```java -jar .\textidote.jar-0.9.jar --read-all --check fr .\main.tex``` is the same

```
Exception in thread "main" java.lang.StackOverflowError
        at java.util.stream.Streams$ConcatSpliterator.estimateSize(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.estimateSize(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.estimateSize(Unknown Source) 
```

**Comment by sylvainhalle** [comment]
Thanks for your feedback. We'll need to dig further to understand why I don't get this error and you do. I am sure the answer will be instructive once we find what the problem is.

If I were to bet on the root cause right now, I would say this is related with the default encoding used by Windows (I see in your typeout that `Hallé` is output as `HallΘ`, which is a telltale sign that something might be off.) The future will say if I am right. ;-)

To start with, could you tell me what OS (I suspect Windows?) and version of Java you are using by typing:

```
java -version
```

Thanks!

**Comment by Louddy** [comment]
Hello Sylvain, I have the same error.
I am using Java 8 (build 1.8.0_371-b11)

**Comment by sylvainhalle** [comment]
I'll try to run the program on a Windows machine and see what I get.

**Comment by Louddy** [comment]
I will try on another machine.

**Comment by Biorix** [comment]
Windows 11 22H2

But how does the Windows encoding could influence the results if it's working in English, German, and Spanish?

**Comment by Louddy** [comment]
Ok it was Java.

**Comment by Louddy** [comment]
On the java website there are 3 options for windows: https://www.java.com/en/download/manual.jsp.

The first one cause the error, the third one works.
