### ISSUE TITLE
Big performance decrease after Annotated String introduction

### ISSUE THREAD

**Issue by vmartinv** [sylvainhalle/textidote#234]
I have a document (around 100 pages) that takes around 30/50 seconds to be processed in the latest release (v0.8.3).
At the moment in master it takes 10 minutes to process the same document. I did a git bisect and tracked down the problem to "Re-implementation of AnnotatedString" (commit 4676594). Is there a reason why this could be happening?

- The delay seems to be spread out across the different chapters.
- `--clean` works very fast, so I think is not related to the cleaner.

**Comment by sylvainhalle** [comment]
I expected the re-implementation of AnnotatedString to be a bit slower than the old one, but not by such a large factor.

However, what makes me doubt that this is only caused by this class is that you mention that cleaning works fast --yet this option performs the same operations on the input string as `--check', which would indicate the problem is further down in the pipeline. 

I'll need to look into it to understand why this is the case.

**Comment by sylvainhalle** [comment]
Did some profiling; it turns out that the way in which character ranges are tracked does not scale well for large documents.

![Screenshot from 2023-10-20 11-09-57](https://github.com/sylvainhalle/textidote/assets/1533065/a5f5f919-58cd-4e50-b9cd-508767189904)

Calculating the input range corresponding to an output range is currently done by calculating the explanation tree of an internal chain of Petit Poucet `Function` objects, which, for large LaTeX files with multiple transformations, can reach thousands of functions.

I am currently working on a modified version of `AnnotatedString` that directly updates the input-output mapping every time a transformation is applied.

**Comment by vmartinv** [comment]
That sounds good btw, but maybe an overkill since we only need to compute the input-output mapping once: right after the cleaning and before the checks/linters.
So maybe I can suggest that functions such as `findOriginalRange` use an internally cached input-output mapping (and if it's not available compute it, because we already know that these functions happen after all transformations are applied)

**Comment by sylvainhalle** [comment]
I just push a modification to `AnnotatedString` that updates an input-output mapping instead of building an explanation tree from a long circuit of functions.

I tested on a 300 kb LaTeX file; I killed the previous version after ~4 minutes, while the new version produces a report in about 25 seconds. This is still slower than the original `AnnotatedString`, but at least restores reasonable performance for the 0.9 alpha release.

**Comment by vmartinv** [comment]
It works great! Now my document take 40 seconds just like on v0.8. Thank you for this optimisation!

**Comment by sylvainhalle** [comment]
It could be even better because there are still a couple of things that are recalculated by every rule (e.g. line position of a given character in the file). I'll leave that for a future release since the performance is roughly back to what it was in 0.8.
