### ISSUE TITLE
Use the report.html to work with browser extensions like grammarly

### ISSUE THREAD

**Issue by arac-id** [sylvainhalle/textidote#42]
I would like to thank Sylvain for this very useful tool.

After producing the report.html I got the idea of trying the Grammarly and Ginger chrome extensions on the HTML file but didn't work. Even opening the file with Jupyterlab, the extensions failed. I did a test online and Grammarly homepage picked up some mistakes that went through me. 

I would appreciate if the textidote HTML file could work with these chrome extensions.

Best Regards,
André

**Comment by sylvainhalle** [comment]
Could you give me an example file/screenshot of what you see?

**Comment by arac-id** [comment]
Sure. I'm using Opera browser, it is compatible with chrome extensions. 

![ginger-textidote](https://user-images.githubusercontent.com/33530184/47373149-9a444e00-d6c1-11e8-97dc-7cf4d78d91dc.png)

However, If I open a homepage editor like Hemingway app, we can see the ginger extension working.

![editor-ginger](https://user-images.githubusercontent.com/33530184/47373879-168b6100-d6c3-11e8-88b2-d019437e2ab5.png)

**Comment by sylvainhalle** [comment]
The problem is that the Ginger extension does not work on local files opened with the *File/Open* menu. I made a test by putting a TeXtidote report online on a web server, and suddenly Ginger works on it, see screenshot:

![ginger](https://user-images.githubusercontent.com/1533065/47412344-d03e0c80-d76b-11e8-84d4-a38ff57f4bae.png)

So unfortunately, the problem is not with TeXtidote, but with the Ginger extension. Unless you upload your reports online, it won't be able to process them. I suggest you forward this issue to the Ginger developers.

Thanks for your comment!
