### ISSUE TITLE
Upgrade to latest version of LanguageTool

### ISSUE THREAD

**Issue by sylvainhalle** [sylvainhalle/textidote#52]
Current build of TeXtidote includes LanguageTool 4.1. As of 2019-01-06, the latest version is 4.4. See: https://languagetool.org/download/

**Comment by Backfighter** [comment]
I've seen that you bundle languagetools yourself which seems to be very tedious. You could use the artifact from the maven repository of languagetool (https://repo1.maven.org/maven2/org/languagetool/language-all/4.4/language-all-4.4.jar) in your config.xml. 
I would also recommend switching from ant to maven as the build system since it makes dependency management easier.

**Comment by sylvainhalle** [comment]
The file at the end of this URL is only 2 kilobytes, and does not appear to be either a valid JAR or ZIP file.

**Comment by Backfighter** [comment]
Oh you're right languagetool-all is basically a group, gathering all language specific jars as dependencies. Therefore they are not included (https://mvnrepository.com/artifact/org.languagetool/language-all/4.4). I guess I  jumped the gun on this one. Sorry. 

This only leaves using a build tool that supports maven as an option to allow easier upgrades of the language tool (maven, gradle, ivy,... ). 
Which I would still recommend.
