### ISSUE TITLE
The first line of a file is not correctly handled

### ISSUE THREAD

**Issue by pagabuc** [sylvainhalle/textidote#63]
Hey sylvainhalle,

First of all thanks for the awesome tool!
While testing it, I noticed that textidote does not correctly handle the first line of input.

MWE:
```latex
\section{Appendix}
Our approach follow a certain set of rules.
Our approach follow a certain set of rules.
```

And this is the output of the tool, when run with ` --read-all --check en`:
```
TeXtidote v0.7.1 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain Hallé - All rights reserved

Found 2 warning(s)
Total analysis time: 1 second(s)

* L1C2-L1C9 This section is very short (about 17 words). You should consider 
  merging it with another section or make it longer. [sh:seclen] 
  \section{Appendix}
   ^^^^^^^^
* L4C14-L4C20 Possible agreement error - use third-person verb forms for 
  singular and mass nouns: 'follows'.. Suggestions: 
  [follows] (66) [lt:en:MASS_AGREEMENT] 
  Our approach follow a certain set of rules.
               ^^^^^^^
```

Is this a bug or I am doing something wrong? 
Thanks!

**Comment by pagabuc** [comment]
On the other hand, when I run the tool against this file:
```latex
\begin{document}
Our approach follow a certain set of rules.
\end{document}
```
it works as expected! It might be related to the `--read-all` parameter?

**Comment by sylvainhalle** [comment]
Hi! The problem is caused by the fact that there is no blank line between the `\section` command and the rest of the text. When TeXtidote cleans the markup, the file that is being sent to LanguageTool is this:

```
Appendix
Our approach follow a certain set of rules.
Our approach follow a certain set of rules.
```

LanguageTool does not know that Appendix is a title; it takes it as part of the sentence that continues on the line after. Apparently, it cannot make sense of it, and this is why it does not report an error on the first occurrence of "follow". There's not much I can do on my side, apart from encouraging people to separate headings from text in their sources.
