### ISSUE TITLE
Subfiles: textidote doesn't find my subfiles (\input)

### ISSUE THREAD

**Issue by sim590** [sylvainhalle/textidote#64]
Let the following minimal example:
```tex
\documentclass[12pt]{article}
\begin{document}
\input{toto}
\end{document}

```
with `toto.tex` containing some text. Running the following:

```
textidote --check fr main.tex
```
produces:
```
TeXtidote v0.7.1 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain Hallé - All rights reserved

File /toto not found (skipping)
Found 0 warning(s)
Total analysis time: 0 second(s)

Everything is OK!
```
It cannot find `toto.tex` even though the PDF file is compiled correctly. Changing `\input{toto}` to `\input{toto.tex}` doesn't help. What's wrong?

**Comment by sylvainhalle** [comment]
TeXtidote is not reading `toto.tex`, because its contents are not enclosed between `\begin{document}`/`\end{document}`. The `--read-all` option is what you need.

**Comment by sim590** [comment]
Even though I add `--read-all`, the file is not read. I have the same result.

**Comment by sim590** [comment]
It seems like I have to add `toto.tex` in the list of files on the command line even though the documentation seems to imply that textidote should follow the `\input`s by itself.

**Comment by sim590** [comment]
I have just tried it in a docker image and it works there, but not on my regular environment. That is, the following works:

```
$ textidote --read-all --check fr main.tex
```

as you suggested. Outside of docker, I have to add `toto.tex` next to `main.tex`. That's weird. I'm wondering what's the difference.

**Comment by sylvainhalle** [comment]
This is strange indeed. I'll reopen and investigate further.

**Comment by rosslaird** [comment]
I'm having the same issue (on Arch). My \input files are ignored with --read-all.

**Comment by PinkieSwirl** [comment]
Same issue on windows 10

```
java -jar textidote.jar --read-all --html main.tex > report.html
TeXtidote v0.7.1 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain HallΘ - All rights reserved

File \misc/frontpage not found (skipping)
File \chapters/chap_0 not found (skipping)
File \chapters/chap_1 not found (skipping)
File \chapters/chap_2 not found (skipping)
File \chapters/chap_3 not found (skipping)
File \chapters/chap_4 not found (skipping)
File \chapters/chap_5 not found (skipping)
File \chapters/chap_6 not found (skipping)
File \chapters/chap_7 not found (skipping)
File \misc/acronyms not found (skipping)
File \misc/chap_appendix not found (skipping)
Found 14 warning(s)
Total analysis time: 0 second(s)
```
My inputs look like this: ``\input{chapters/chap_1}``
Changing it to ``\input{chapters/chap_1.tex}`` does not fix it.

Adding the files manually to the command works, but still produces above output (skipping..).

The document compiles fine.

**Comment by samuelstjean** [comment]
I have the same issue, it looks like it is trying to read from the root folder instead of the local folder somehow, for example my document contains
~~~latex
% \input{tex/intro.tex}
\input{tex/theory.tex}
% \input{tex/method.tex}
% \input{tex/experiments.tex}
% \input{tex/results.tex}
\input{tex/discussion.tex}
% \input{tex/conclusion.tex}
% \input{tex/appendix.tex}
~~~

which works fine for building the document (I use it to comment/uncomment subsections to work with). From textidote, I get this output

~~~bash
samuel ~/projects/noise_floor_effects/latex $ [latex (master)] textidote --html --check en --read-all main.tex > main.html
TeXtidote v0.7.1 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain Hallé - All rights reserved

File /tex/header.tex not found (skipping)
File /tex/theory.tex not found (skipping)
File /tex/discussion.tex not found (skipping)
Found 28 warning(s)
Total analysis time: 3 second(s)
~~~

If I change the previous lines to use relative paths instead, I get as an output
~~~bash
samuel ~/projects/noise_floor_effects/latex $ [latex (master)] textidote --html --check en --read-all main.tex > main.html
TeXtidote v0.7.1 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain Hallé - All rights reserved

File /./tex/header.tex not found (skipping)
File /./tex/theory.tex not found (skipping)
File /./tex/discussion.tex not found (skipping)
Found 28 warning(s)
Total analysis time: 2 second(s)
~~~

Kind of like if it was always trying to read my partial documents from the root folder somehow, would that be the root cause of the issue? (pun fully intended). This is on ubuntu 16.04, and regarding the above post, if that's the issue, looks like the / and \ are not correctly use as windows would expect them I'd guess.

**Comment by sylvainhalle** [comment]
Thanks for the detailed diagnostics; I found where the problem is. I'll push a fix shortly.

**Comment by PinkieSwirl** [comment]
@sylvainhalle Did any further problems occur?

**Comment by haidaoxiaofei** [comment]
@sylvainhalle I find the grammar errors in input files cannot be detected! I tested, for example "He are bad" in subfiles cannot be detected, but it can be detected in the top level tex file. Do you have any idea about it?

By the way, I have a trick to "fix" the subfiles cannot be found bug, use the alias below:

texcheck='f(){ java -jar /Users/bigstone/workspace/myTools/textidote.jar --check en --html \`pwd\`/$1  > report.html }; f'

I find the problem is the getParent function cannot return the parent path, if the file path is relative path.

**Comment by sylvainhalle** [comment]
You're right, the problem is in `getParent`. I'll push a fixed version as soon as I have some time!

**Comment by jeremyfix** [comment]
I had the same issue ; but then , it is solved by running
`textidote --check fr ./main.tex` instead of `textidote --check fr main.tex` 

Just notice the full path before the filename which is probably also what the alias of @haidaoxiaofei  is doing.

**Comment by JorricksTU** [comment]
> I had the same issue ; but then , it is solved by running
> `textidote --check fr ./main.tex` instead of `textidote --check fr main.tex`
> 
> Just notice the full path before the filename which is probably also what the alias of @haidaoxiaofei is doing.

This fixed the problem for me! Thank you for your update.

**Comment by domoritz** [comment]
Unfortunately, I have to both add `.tex` and use `./main.tex` as an argument. However, then there are errors with inputs in files inside folders.

**Comment by sylvainhalle** [comment]
Just checked with the latest version in the master branch, and the problem seems to be solved (although I can't remember _when_ I changed something). Feel free to reopen if it still doesn't work.
