### ISSUE TITLE
Why not using AnnotatedText

### ISSUE THREAD

**Issue by PierreMarchand20** [sylvainhalle/textidote#80]
I am looking around the repository, and I am wondering: why did not you use AnnotatedText as explained here (http://wiki.languagetool.org/java-api) ? it is not practical ?

**Comment by sylvainhalle** [comment]
First off, I shall say that in the current state of the program, I don't plan to turn everything around in the code to use the annotated strings provided by LanguageTool. ;-)

When I started coding, my main design arguments for not using them was:

- To create such an object, you need to *parse* the original LaTeX file in order to insert the markup chunks and the text chunks one by one. As I said in #56, I don't want to end up writing a LaTeX parser or interpreter. In contrast, what TeXtidote does is much simpler: a handful of regex find/replace operations on the original text.
- I plan to reuse the `AnnotatedString` class on some other project (not done yet) where `AnnotatedText` could not be used in replacement, so there was sense in investing time to create this class.

**Comment by PierreMarchand20** [comment]
Ok, thank you for your answer ! I was just curious ^^
