### ISSUE TITLE
[Feature request] possibility to provide plagiarism checking

### ISSUE THREAD

**Issue by kirk86** [sylvainhalle/textidote#85]
Thanks for this great app, I was wondering if there are any road maps to incorporate tools such as text analyzers in order to provide plagiarism checking abilities. That would have been something useful and a nice overall addition to this nice app.

**Comment by sylvainhalle** [comment]
Thanks!

I never thought of such a possible use. The easiest way I see would be to use the `--clean` option to obtain a clear-text version of the original, which you could then pipe into such a tool.

However, in order to remain in the philosophy of "keep it simple", I'd leave that outside of TeXtidote. Besides, I think most of these tools are online platforms anyway, so an integration to them would not be so easy.

Does that make sense to you?

**Comment by kirk86** [comment]
@sylvainhalle 

> Does that make sense to you?

Absolutely!

Thanks for taking time to reply. 



> Besides, I think most of these tools are online platforms anyway

That's sadly true, especially the fact that there are not open source alternatives. The community would benefit greatly from those contributions IMHO.
